export const RELATIONSHIPS_MAP: Map<RegExp, string> = new Map<RegExp, string>([
  [/^pF$/, 'Мама'],
  [/^pM$/, 'Папа'],
  [/^p[M|F]-pF$/, 'Бабушка'],
  [/^p[M|F]-pM$/, 'Дедушка'],
  [/^p[M|F]-cF$/, 'Сестра'],
  [/^p[M|F]-cM$/, 'Брат'],
  [/^p[M|F]-c[M|F]-pF$/, 'Мачеха'],
  [/^p[M|F]-c[M|F]-pM$/, 'Отчим'],
  [/^p[M|F]-p[M|F]-pF$/, 'Прабабушка'],
  [/^p[M|F]-p[M|F]-pM$/, 'Прадедушка'],
  [/^p[M|F]-p[M|F]-cF$/, 'Тетя'],
  [/^p[M|F]-p[M|F]-cM$/, 'Дядя'],
  [/^p[M|F]-p[M|F]-p[M|F]-cF$/, 'Внучатая тетя'],
  [/^p[M|F]-p[M|F]-p[M|F]-cM$/, 'Внучатый дядя'],
]);