FROM node:alpine as builder
WORKDIR /app
COPY package.json package-lock.json /app
RUN npm ci
COPY . /app
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html