import { IRelative } from './relative';

export const DEFAULT_DATA: IRelative[] = [
  { key: -2, name: 'Надежда', lastName: 'Шишмарёва', gender: 'F' },
  { key: -1, name: 'Иван', lastName: 'Шишмарёв', middleName: 'Ларионович', gender: 'M' },
  { key: -3, name: 'Валентина', lastName: 'Шишмарёва', middleName: 'Ивановна', gender: 'F', parents: [-1, -2] },
  { key: 0, name: 'Александр', lastName: 'Шишмарёв', middleName: 'Иванович', gender: 'M', parents: [-1, -2] },
  { key: -4, name: 'Иван', lastName: 'Михайлик', middleName: 'Савельевич', gender: "M" },
  { key: -5, name: 'Мария', lastName: 'Михайлик', middleName: 'Григорьевна', gender: "F" },
  { key: -6, name: 'Виктор', lastName: 'Михайлик', middleName: 'Иванович', gender: "M", parents: [-4, -5] },
  { key: -7, name: 'Григорий', lastName: 'Михайлик', middleName: 'Иванович', gender: "M", parents: [-4, -5] },
  { key: -8, name: 'Александра', lastName: 'Михайлик', middleName: 'Ивановна', gender: "F", parents: [-4, -5] },
  { key: -9, name: 'Валентина', lastName: 'Михайлик', middleName: 'Ивановна', gender: "F", parents: [-4, -5] },
  { key: -10, name: 'Валерий', lastName: 'Михайлик', middleName: 'Иванович', gender: "M", parents: [-4, -5] },
  { key: 1, name: 'Елена', lastName: 'Шишмарёва', middleName: 'Ивановна', gender: 'F', parents: [-4, -5] },
  { key: 2, name: 'Ольга', lastName: 'Орлова', middleName: 'Александровна', gender: 'F', parents: [0, 1] },
  { key: 3, name: 'Иван', lastName: 'Шишмарёв', middleName: 'Александрович', gender: 'M', parents: [0, 1] },
  { key: 9, name: 'Ольга', lastName: 'Шишмарёва (наверное)', gender: 'F' },
  { key: 10, name: 'Савелий', lastName: 'Шишмарёв', middleName: 'Иванович', gender: 'M', parents: [3, 9] },
  { key: 11, name: 'Ростислав', lastName: 'Шишмарёв', middleName: 'Иванович', gender: 'M', parents: [3, 9] },
  { key: 12, name: 'Данна', lastName: 'Шишмарёва', middleName: 'Ивановна', gender: 'F', parents: [3, 9] },
  { key: 4, name: 'Алексей', lastName: 'Орлов', middleName: 'Владимирович', gender: 'M' },
  { key: 5, name: 'Алина', lastName: 'Орлова', middleName: 'Алексеевна', gender: 'F', parents: [2, 4] },
  { key: 6, name: 'Антон', lastName: 'Орлов', middleName: 'Алексеевич', gender: 'M', parents: [2, 4] },
  { key: 7, name: 'Сергей', lastName: 'Клачков', middleName: 'Евгеньевич', gender: 'M', parents: [17, 18] },
  { key: 13, name: 'Андрей', lastName: 'Клачков', middleName: 'Евгеньевич', gender: 'M', parents: [17, 18] },
  { key: 14, name: 'Ольга', lastName: 'Клачкова (наверное)', gender: 'F' },
  { key: 15, name: 'Арина', lastName: 'Клачкова', middleName: 'Андреевна', gender: 'F', parents: [13, 14] },
  { key: 16, name: 'Катя', lastName: 'Клачкова', middleName: 'Андреевна', gender: 'F', parents: [13, 14] },
  { key: 17, name: 'Галина', lastName: 'Клачкова', gender: 'F', parents: [21, 22] },
  { key: 18, name: 'Евгений', lastName: 'Клачков', middleName: 'Федорович', gender: 'M', parents: [19, 20] },
  { key: 23, name: 'Татьяна', lastName: 'Михайлова', gender: 'F', parents: [19, 20] },
  { key: 24, name: 'Владимир', lastName: '', gender: 'M' },
  { key: 25, name: 'Женя', lastName: 'Михайлова', gender: 'M', parents: [23, 24] },
  { key: 26, name: 'Костя', lastName: 'Михайлов', gender: 'M', parents: [23, 24] },
  { key: 19, name: 'Валентина', lastName: 'Клачкова', middleName: 'Федоровна', gender: 'F' },
  { key: 20, name: 'Фёдор', lastName: 'Клачков', gender: 'M' },
  { key: 21, name: 'Андрей', lastName: 'Краснокуцкий', gender: 'M' },
  { key: 22, name: 'Мария', lastName: 'Краснокуцкая', gender: 'F' },
  { key: 8, name: 'Валерий', lastName: 'Клачков', middleName: 'Валентинович', gender: 'M', parents: [2, 7] }
];