import { IRelative } from './relative';

export const DEFAULT_DATA: IRelative[] = [
  { key: 1, name: 'Надежда', lastName: 'Шишмарёва', gender: 'F' },
  { key: 2, name: 'Иван', lastName: 'Шишмарёв', middleName: 'Ларионович', gender: 'M' },
  { key: 3, name: 'Валентина', lastName: 'Шишмарёва', middleName: 'Ивановна', gender: 'F', parents: [2, 1] },
  { key: 4, name: 'Александр', lastName: 'Шишмарёв', middleName: 'Иванович', gender: 'M', parents: [2, 1] },
  { key: 5, name: 'Иван', lastName: 'Михайлик', middleName: 'Савельевич', gender: "M" },
  { key: 6, name: 'Мария', lastName: 'Михайлик', middleName: 'Григорьевна', gender: "F" },
  { key: 7, name: 'Виктор', lastName: 'Михайлик', middleName: 'Иванович', gender: "M", parents: [5, 6] },
  { key: 8, name: 'Григорий', lastName: 'Михайлик', middleName: 'Иванович', gender: "M", parents: [5, 6] },
  { key: 9, name: 'Александра', lastName: 'Михайлик', middleName: 'Ивановна', gender: "F", parents: [5, 6] },
  { key: 10, name: 'Валентина', lastName: 'Михайлик', middleName: 'Ивановна', gender: "F", parents: [5, 6] },
  { key: 11, name: 'Валерий', lastName: 'Михайлик', middleName: 'Иванович', gender: "M", parents: [5, 6] },
  { key: 12, name: 'Елена', lastName: 'Шишмарёва', middleName: 'Ивановна', gender: 'F', parents: [5, 6] },
  { key: 13, name: 'Ольга', lastName: 'Орлова', middleName: 'Александровна', gender: 'F', parents: [4, 12] },
  { key: 14, name: 'Иван', lastName: 'Шишмарёв', middleName: 'Александрович', gender: 'M', parents: [4, 12] },
  { key: 15, name: 'Ольга', lastName: 'Шишмарёва', gender: 'F' },
  { key: 16, name: 'Савелий', lastName: 'Шишмарёв', middleName: 'Иванович', gender: 'M', parents: [14, 15] },
  { key: 17, name: 'Ростислав', lastName: 'Шишмарёв', middleName: 'Иванович', gender: 'M', parents: [14, 15] },
  { key: 18, name: 'Данна', lastName: 'Шишмарёва', middleName: 'Ивановна', gender: 'F', parents: [14, 15] },
  { key: 19, name: 'Алексей', lastName: 'Орлов', middleName: 'Владимирович', gender: 'M' },
  { key: 20, name: 'Алина', lastName: 'Орлова', middleName: 'Алексеевна', gender: 'F', parents: [13, 19] },
  { key: 21, name: 'Антон', lastName: 'Орлов', middleName: 'Алексеевич', gender: 'M', parents: [13, 19] },
  { key: 22, name: 'Сергей', lastName: 'Клачков', middleName: 'Евгеньевич', gender: 'M', parents: [27, 28] },
  { key: 23, name: 'Андрей', lastName: 'Клачков', middleName: 'Евгеньевич', gender: 'M', parents: [27, 28] },
  { key: 24, name: 'Ольга', lastName: 'Клачкова', gender: 'F' },
  { key: 25, name: 'Арина', lastName: 'Клачкова', middleName: 'Андреевна', gender: 'F', parents: [23, 24] },
  { key: 26, name: 'Катя', lastName: 'Клачкова', middleName: 'Андреевна', gender: 'F', parents: [23, 24] },
  { key: 27, name: 'Галина', lastName: 'Клачкова', gender: 'F', parents: [35, 36] },
  { key: 28, name: 'Евгений', lastName: 'Клачков', middleName: 'Федорович', gender: 'M', parents: [33, 34] },
  { key: 29, name: 'Татьяна', lastName: 'Михайлова', gender: 'F', parents: [33, 34] },
  { key: 30, name: 'Владислав', lastName: '', gender: 'M' },
  { key: 31, name: 'Женя', lastName: 'Михайлова', gender: 'M', parents: [29, 30] },
  { key: 32, name: 'Костя', lastName: 'Михайлов', gender: 'M', parents: [29, 30] },
  { key: 33, name: 'Валентина', lastName: 'Клачкова', middleName: 'Федоровна', gender: 'F' },
  { key: 34, name: 'Фёдор', lastName: 'Клачков', gender: 'M' },
  { key: 35, name: 'Андрей', lastName: 'Краснокуцкий', gender: 'M' },
  { key: 36, name: 'Мария', lastName: 'Краснокуцкая', gender: 'F' },
  { key: 37, name: 'Валера', lastName: 'Клачков', middleName: 'Валентинович', gender: 'M', parents: [13, 22] }
];